version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
    command: --smallfiles
  app:
    image: alerts-mongo-kotlin
    ports:
    - 8080:8080
    links:
    - mongodb

volumes:
  mongodb_container: